from __future__ import annotations

from typing import Protocol

from campfire_cli.app.migration.schema.migration_schema import (
    InventoryItem,
    MigrationPlan,
    MigrationResult,
)


class MigrationRepositoryProtocol(Protocol):
    def save_batch(self, batch_uuid: str, batch: str, scope: str, config_hash: str) -> None: ...
    def save_inventory(self, batch: str, items: list[InventoryItem]) -> None: ...
    def load_inventory(self, batch: str) -> tuple[str, str, list[InventoryItem]]: ...
    def save_plan(self, plan: MigrationPlan) -> None: ...
    def load_plan(self, batch: str) -> MigrationPlan: ...
    def save_execution(self, result: MigrationResult) -> None: ...
    def save_verification(self, result: MigrationResult) -> None: ...
