from __future__ import annotations

from typing import Protocol

from campfire_cli.app.workspace.schema.restructure_schema import (
    InventoryItem,
    RestructurePlan,
    RestructureResult,
)


class RestructureRepositoryProtocol(Protocol):
    def save_batch(self, batch_uuid: str, batch: str, scope: str, config_hash: str) -> None: ...
    def save_inventory(self, batch: str, items: list[InventoryItem]) -> None: ...
    def load_inventory(self, batch: str) -> tuple[str, str, list[InventoryItem]]: ...
    def save_plan(self, plan: RestructurePlan) -> None: ...
    def load_plan(self, batch: str) -> RestructurePlan: ...
    def save_execution(self, result: RestructureResult) -> None: ...
    def save_verification(self, result: RestructureResult) -> None: ...
