from __future__ import annotations

from pathlib import Path
from typing import Protocol

from campfire_cli.app.workspace.schema.workspace_schema import ProjectEntry, WorkspaceRegistry


class WorkspaceRepositoryProtocol(Protocol):
    def load_registry(self) -> WorkspaceRegistry: ...

    def save_registry(self, registry: WorkspaceRegistry) -> None: ...

    def list_projects(self, workspace_id: str | None = None) -> list[ProjectEntry]: ...

    def get_project(self, project_id: str) -> ProjectEntry | None: ...

    def save_project(self, project: ProjectEntry) -> str: ...

    def save_projects(self, projects: list[ProjectEntry]) -> None: ...

    def replace_projects(self, workspace_id: str, projects: list[ProjectEntry]) -> None: ...

    def replace_registry(
        self, registry: WorkspaceRegistry, projects: list[ProjectEntry]
    ) -> None: ...

    def create_scaffold(self, root: Path, directories: tuple[str, ...]) -> list[str]: ...
