from __future__ import annotations

from typing import Any


def default_configs() -> dict[str, dict[str, Any]]:
    """Return portable defaults for a newly managed Vault."""
    return {
        "governance.json": {
            "version": 1,
            "managed_roots": [],
            "inbox": "_收件箱",
            "domain_marker": "_领域.md",
            "ignored_directories": ["assets", "archive", "generated"],
            "project_reserved_directories": ["任务", "记录", "archive", "_总览", "a_skill"],
        },
        "document-types.json": {
            "version": 1,
            "scope_roots": ["mynote", "mywork"],
            "ignored_directories": ["assets", "archive", "generated"],
            "exempt_basenames": ["_领域.md"],
            "profiles": {
                "project-docs": [
                    "product-spec",
                    "tech-spec",
                    "decision",
                    "plan",
                    "issue",
                    "record",
                ]
            },
            "types": {
                "moc": {"prefix": "MOC-", "label": "索引"},
                "product-spec": {"prefix": "产品-", "label": "产品"},
                "tech-spec": {"prefix": "技术-", "label": "技术"},
                "decision": {"prefix": "决策-", "label": "决策"},
                "plan": {"prefix": "计划-", "label": "计划"},
                "task": {"prefix": "任务-", "label": "任务"},
                "issue": {"prefix": "问题-", "label": "问题"},
                "record": {"prefix": "记录-", "label": "记录"},
                "knowledge": {"prefix": "知识-", "label": "知识"},
                "prompt": {"prefix": "提示词-", "label": "提示词"},
            },
        },
        "frontmatter-schema.json": {
            "version": 1,
            "field_order": [
                "name",
                "description",
                "type",
                "project",
                "domain",
                "domain_id",
                "task_id",
                "status",
                "lifecycle",
                "priority",
                "assignee",
                "requires_human",
                "blocked_reason",
                "task_source",
                "source_channel",
                "requested_by",
                "created",
                "updated",
                "started",
                "due",
                "completed",
                "result_summary",
                "impact_summary",
                "deliverables",
                "verification",
                "tags",
                "aliases",
                "sources",
                "related",
                "superseded_by",
                "archive_requested",
                "archive_requested_by",
                "archive_requested_at",
                "archive_reason",
                "archived_at",
            ],
            "base": {
                "required": [
                    "name",
                    "description",
                    "type",
                    "status",
                    "created",
                    "updated",
                    "tags",
                ],
                "enums": {"status": ["draft", "current", "archived"]},
                "lists": ["tags"],
                "dates": ["created", "updated"],
            },
            "profiles": {
                "project-docs": {
                    "types": [
                        "product-spec",
                        "tech-spec",
                        "decision",
                        "plan",
                        "issue",
                        "record",
                    ],
                    "required": ["project", "domain", "lifecycle", "related", "superseded_by"],
                    "enums": {"lifecycle": ["maintained", "proposed", "completed", "archived"]},
                    "lists": ["related", "superseded_by"],
                },
                "task": {
                    "types": ["task"],
                    "required": [
                        "task_id",
                        "project",
                        "domain",
                        "lifecycle",
                        "task_source",
                        "source_channel",
                        "assignee",
                        "requires_human",
                        "related",
                    ],
                    "enums": {
                        "lifecycle": [
                            "todo",
                            "in-progress",
                            "blocked",
                            "review",
                            "completed",
                            "cancelled",
                            "archived",
                        ],
                        "task_source": ["personal", "assigned"],
                        "source_channel": ["self", "agent", "oral", "im", "meeting", "email"],
                        "priority": ["urgent", "high", "medium", "low"],
                    },
                    "lists": ["assignee", "deliverables", "verification", "related"],
                    "dates": ["started", "due", "completed"],
                },
            },
        },
        "skills.json": {
            "version": 1,
            "targets": ["~/.claude/skills", "~/.agents/skills"],
            "managed_skills": [
                "campfire-workspace-governance",
                "campfire-conversation-intake",
                "campfire-inbox-triage",
                "mynote-knowledge-governance",
                "mywork-project-docs-governance",
                "mywork-weekly-report-writing",
                "mywork-task-governance",
            ],
            "unknown_skill_policy": "ignore",
            "orphaned_skill_policy": "report",
        },
        "bases.json": {
            "version": 1,
            "target": "治理视图",
            "managed_bases": [
                "Vault文档治理.base",
                "项目文档.base",
                "待归档文档.base",
                "收件箱治理.base",
                "任务工作台.base",
            ],
            "unknown_base_policy": "ignore",
            "orphaned_base_policy": "report",
        },
    }
